version: "3.3"

services:
  web:
    image: niklasfrank/whisper
    ports:
      - "81:80"
    depends_on:
      - "redis"
    networks:
      - "frontend"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - VIRTUAL_HOST=whisper.nikz.se

  redis:
    image: redis:3.2-alpine
    ports:
      - "6379"
    networks:
      - "frontend"

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "5001:5001"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend: