version: "3.3"

services:
  web:
    build: .
    image: niklasfrank/whisper
    ports:
      - "81:80"
    networks:
      - "frontend"

  redis:
    image: redis:3.2-alpine
    container_name: redis
    ports:
      - "6379"
    networks:
      - "frontend"

networks:
 frontend: